[package]
name = "falsec-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
falsec-types = { version = "0.1.0", path = "../falsec-types" }
falsec-util = { version = "0.1.0", path = "../falsec-util" }
