[package]
name = "falsec-analyzer"
version = "0.1.2"
edition = "2024"

[dependencies]
falsec-types = { version = "0.1.1", path = "../falsec-types" }
falsec-util = { version = "0.1.1", path = "../falsec-util" }
