[package]
name = "falsec-compiler"
version = "0.1.2"
edition = "2021"

[dependencies]
falsec-types = { version = "0.1.0", path = "../falsec-types" }
falsec-util = { version = "0.1.0", path = "../falsec-util" }
tempfile = "3.15.0"
