name: Release

permissions:
  contents: write

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Build binary
        run: cargo build --release

      - name: Derive version
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Stage release files
        run: |
          mkdir -p falsec-bin-${{ env.VERSION }}/bin
          mkdir -p falsec-bin-${{ env.VERSION }}/completion

          cp target/release/falsec falsec-bin-${{ env.VERSION }}/bin/
          cp completion/falsec.bash falsec-bin-${{ env.VERSION }}/completion/
          cp completion/falsec.elv falsec-bin-${{ env.VERSION }}/completion/
          cp completion/falsec.fish falsec-bin-${{ env.VERSION }}/completion/
          cp completion/falsec.zsh falsec-bin-${{ env.VERSION }}/completion/
          cp LICENSE falsec-bin-${{ env.VERSION }}/

      - name: Create tarball
        run: |
          tar -czf falsec-bin-${{ env.VERSION }}-x86_64.tar.gz falsec-bin-${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ env.VERSION }}
          files: falsec-bin-${{ env.VERSION }}-x86_64.tar.gz
